
// This file contains mock data for products and categories

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  inStock: boolean;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
}

export const categories: Category[] = [
  { id: 'food', name: 'Food', icon: 'utensils' },
  { id: 'toiletries', name: 'Toiletries', icon: 'shower' },
  { id: 'stationery', name: 'Stationery', icon: 'pencil' },
  { id: 'clothing', name: 'Clothing', icon: 'shirt' },
  { id: 'grains', name: 'Grains', icon: 'wheat' },
];

export const products: Product[] = [
  // Food Category
  {
    id: 'food-1',
    name: 'Amul Butter',
    description: 'Pasteurized table butter, 500g pack',
    price: 245,
    category: 'food',
    image: '/src/assets/amul-butter.png',
    inStock: true,
  },
  {
    id: 'food-2',
    name: 'Maggi Noodles',
    description: 'Instant noodles, pack of 6',
    price: 12,
    category: 'food',
    image: '/src/assets/maggi-noodles.png',
    inStock: true,
  },
  {
    id: 'food-3',
    name: 'MTR Sambar Powder',
    description: 'Traditional South Indian spice mix, 200g',
    price: 125,
    category: 'food',
    image: '/src/assets/mtr-sambar-powder.png',
    inStock: true,
  },
  {
    id: 'food-4',
    name: 'Haldiram Bhujia',
    description: 'Crispy snack, 1kg pack',
    price: 210,
    category: 'food',
    image: '/src/assets/haldiram-bhujia.png',
    inStock: true,
  },
  {
    id: 'food-5',
    name: 'MDH Garam Masala',
    description: 'Aromatic Indian spice blend, 100g',
    price: 85,
    category: 'food',
    image: '/src/assets/mdh-garam-masala.png',
    inStock: true,
  },
  {
    id: 'food-6',
    name: 'Britannia Good Day Cookies',
    description: 'Butter cookies, 600g pack',
    price: 110,
    category: 'food',
    image: '/src/assets/britannia-good-day-cookies.png',
    inStock: true,
  },
  {
    id: 'food-7',
    name: 'Nestle Everyday Dairy Whitener',
    description: 'Milk powder for tea and coffee, 400g',
    price: 175,
    category: 'food',
    image: '/src/assets/nestle-everyday-dairy-whitener.png',
    inStock: true,
  },
  {
    id: 'food-8',
    name: 'Parle-G Biscuits',
    description: 'Original glucose biscuits, 800g',
    price: 85,
    category: 'food',
    image: '/src/assets/parle-g-biscuits.png',
    inStock: true,
  },
  {
    id: 'food-9',
    name: 'Dabur Honey',
    description: 'Pure honey, 500g bottle',
    price: 220,
    category: 'food',
    image: '/src/assets/dabur-honey.png',
    inStock: true,
  },
  {
    id: 'food-10',
    name: 'Tata Salt',
    description: 'Iodized salt, 1kg pack',
    price: 24,
    category: 'food',
    image: '/src/assets/tata-salt.png',
    inStock: true,
  },
  
  // Toiletries Category
  {
    id: 'toiletries-1',
    name: 'Dove Soap',
    description: 'Moisturizing beauty bar, pack of 3',
    price: 135,
    category: 'toiletries',
    image: '/src/assets/dove-soap.png',
    inStock: true,
  },
  {
    id: 'toiletries-2',
    name: 'Colgate Toothpaste',
    description: 'Advanced cavity protection, 150g',
    price: 90,
    category: 'toiletries',
    image: '/src/assets/colgate-toothpaste.png',
    inStock: true,
  },
  {
    id: 'toiletries-3',
    name: 'Parachute Coconut Oil',
    description: 'Pure coconut oil for hair, 500ml',
    price: 199,
    category: 'toiletries',
    image: '/src/assets/parachute-coconut-oil.png',
    inStock: true,
  },
  {
    id: 'toiletries-4',
    name: 'Dettol Hand Sanitizer',
    description: 'Instant hand sanitizer, 200ml',
    price: 85,
    category: 'toiletries',
    image: '/src/assets/dettol-hand-sanitizer.png',
    inStock: true,
  },
  {
    id: 'toiletries-5',
    name: 'Pears Soap',
    description: 'Gentle care soap, pack of 4',
    price: 180,
    category: 'toiletries',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'toiletries-6',
    name: 'Nivea Body Lotion',
    description: 'Nourishing skin care, 400ml',
    price: 260,
    category: 'toiletries',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'toiletries-7',
    name: 'Clinic Plus Shampoo',
    description: 'Strengthening shampoo, 650ml',
    price: 170,
    category: 'toiletries',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'toiletries-8',
    name: 'Santoor Sandal Soap',
    description: 'Sandal and turmeric soap, pack of 4',
    price: 120,
    category: 'toiletries',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'toiletries-9',
    name: 'Himalaya Face Wash',
    description: 'Purifying neem face wash, 150ml',
    price: 110,
    category: 'toiletries',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'toiletries-10',
    name: 'Gillette Shaving Cream',
    description: 'Classic rich foaming cream, 190g',
    price: 145,
    category: 'toiletries',
    image: '/placeholder.svg',
    inStock: true,
  },
  
  // Stationery Category
  {
    id: 'stationery-1',
    name: 'Classmate Notebook',
    description: 'Single line, 190 pages, pack of 6',
    price: 240,
    category: 'stationery',
    image: '/src/assets/stationery-products.png',
    inStock: true,
  },
  {
    id: 'stationery-2',
    name: 'Reynolds Ball Pen',
    description: 'Blue ink pens, pack of 10',
    price: 50,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-3',
    name: 'Camlin Color Pencils',
    description: 'Set of 24 colors',
    price: 120,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-4',
    name: 'DOMS Pencils',
    description: 'HB pencils, pack of 20',
    price: 70,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-5',
    name: 'Fevicol Adhesive',
    description: 'Strong adhesive, 200g tube',
    price: 60,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-6',
    name: 'Faber-Castell Highlighters',
    description: 'Assorted colors, pack of 5',
    price: 150,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-7',
    name: 'Staedtler Geometry Box',
    description: 'Complete mathematical drawing set',
    price: 199,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-8',
    name: 'Natraj Eraser',
    description: 'Non-dust erasers, pack of 10',
    price: 50,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-9',
    name: 'Kangaroo Stapler',
    description: 'High quality stapler with 1000 pins',
    price: 125,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'stationery-10',
    name: 'Luxor Whiteboard Marker',
    description: 'Pack of 4 assorted colors',
    price: 110,
    category: 'stationery',
    image: '/placeholder.svg',
    inStock: true,
  },
  
  // Clothing Category
  {
    id: 'clothing-1',
    name: 'Jockey Men\'s T-shirt',
    description: 'Round neck, cotton, M size',
    price: 450,
    category: 'clothing',
    image: '/src/assets/clothing-products-new.png',
    inStock: true,
  },
  {
    id: 'clothing-2',
    name: 'Levis Jeans',
    description: 'Slim fit, size 32',
    price: 1999,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-3',
    name: 'Van Heusen Shirt',
    description: 'Formal shirt, cotton blend, L size',
    price: 1499,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-4',
    name: 'Biba Kurti',
    description: 'Ethnic printed, cotton, M size',
    price: 899,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-5',
    name: 'Allen Solly Trousers',
    description: 'Formal pants, size 34',
    price: 1299,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-6',
    name: 'W Women\'s Palazzo',
    description: 'Ethnic wear, free size',
    price: 799,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-7',
    name: 'Bata Men\'s Formal Shoes',
    description: 'Black leather, size 9',
    price: 1799,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-8',
    name: 'Nike Sports Shoes',
    description: 'Running shoes, size 8',
    price: 3499,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-9',
    name: 'Fastrack Sunglasses',
    description: 'UV protection, unisex',
    price: 999,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'clothing-10',
    name: 'Titan Watch',
    description: 'Analog watch for men',
    price: 2499,
    category: 'clothing',
    image: '/placeholder.svg',
    inStock: true,
  },
  
  // Grains Category
  {
    id: 'grains-1',
    name: 'Basmati Rice',
    description: 'Premium long grain, 5kg',
    price: 549,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-2',
    name: 'Toor Dal',
    description: 'Split pigeon peas, 2kg',
    price: 210,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-3',
    name: 'Sooji (Semolina)',
    description: 'Fine grain, 1kg pack',
    price: 55,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-4',
    name: 'Besan (Gram Flour)',
    description: 'Fine ground chickpea flour, 1kg',
    price: 110,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-5',
    name: 'Chana Dal',
    description: 'Split chickpeas, 1kg',
    price: 120,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-6',
    name: 'Moong Dal',
    description: 'Split mung beans, 1kg',
    price: 135,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-7',
    name: 'Rajma (Kidney Beans)',
    description: 'Premium quality, 1kg',
    price: 170,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-8',
    name: 'Poha (Flattened Rice)',
    description: 'Medium thickness, 1kg',
    price: 65,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-9',
    name: 'Atta (Whole Wheat Flour)',
    description: 'Chakki fresh, 10kg',
    price: 399,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
  {
    id: 'grains-10',
    name: 'Maida (All-purpose Flour)',
    description: 'Fine quality, 1kg',
    price: 45,
    category: 'grains',
    image: '/placeholder.svg',
    inStock: true,
  },
];

export const coupons = [
  { code: 'SHOP10', discount: 0.1, description: '10% off your order' },
  { code: 'WELCOME20', discount: 0.2, description: '20% off for new users' },
  { code: 'FREESHIP', discount: 0.05, description: '5% off on all orders' },
];
